// Курс «Топ-100 слов»: самые частотные английские слова.
// prompt — английское слово, answer — русский перевод; hint уточняет
// значение, когда перевод сам по себе неоднозначен (his/him/its и т.п.).

import type { Course, Item } from "./types";

function word(en: string, ru: string, hint?: string): Item {
   return { id: `w:${en}`, prompt: en, answer: ru, hint };
}

const WORDS: Item[] = [
   word("the", "определённый артикль"),
   word("be", "быть"),
   word("to", "к, до (направление); частица перед инфинитивом"),
   word("of", "предлог принадлежности: «чашка чая»"),
   word("and", "и"),
   word("a", "неопределённый артикль"),
   word("in", "в, внутри"),
   word("that", "тот, та, то"),
   word("have", "иметь"),
   word("I", "я"),
   word("it", "оно (о предмете)"),
   word("for", "для"),
   word("not", "не"),
   word("on", "на (поверхности)"),
   word("with", "с, вместе с"),
   word("he", "он"),
   word("as", "как, в качестве"),
   word("you", "ты, вы"),
   word("do", "делать", "вспомогательный глагол"),
   word("at", "у, возле, в (точке)"),
   word("this", "этот, эта, это"),
   word("but", "но"),
   word("his", "его", "чей? (о мужчине)"),
   word("by", "около; посредством"),
   word("from", "из, от (откуда)"),
   word("they", "они"),
   word("we", "мы"),
   word("say", "говорить, сказать"),
   word("her", "её", "о женщине"),
   word("she", "она"),
   word("or", "или"),
   word("an", "неопределённый артикль перед гласной"),
   word("will", "вспомогательный глагол будущего времени"),
   word("my", "мой, моя"),
   word("one", "один"),
   word("all", "все, всё"),
   word("would", "бы (условная форма)"),
   word("there", "там"),
   word("their", "их", "чей?"),
   word("what", "что"),
   word("so", "так, поэтому"),
   word("up", "вверх"),
   word("out", "наружу, вне"),
   word("if", "если"),
   word("about", "о, около"),
   word("who", "кто"),
   word("get", "получать"),
   word("which", "который"),
   word("go", "идти"),
   word("me", "мне, меня"),
   word("when", "когда"),
   word("make", "делать, создавать", "создавать"),
   word("can", "мочь, уметь"),
   word("like", "нравиться; как (похоже)"),
   word("time", "время"),
   word("no", "нет"),
   word("just", "просто; только что"),
   word("him", "его, ему", "кого? кому? (о мужчине)"),
   word("know", "знать"),
   word("take", "брать"),
   word("people", "люди"),
   word("into", "в, внутрь (движение)"),
   word("year", "год"),
   word("your", "твой, ваш"),
   word("good", "хороший"),
   word("some", "некоторые, немного"),
   word("could", "мог бы"),
   word("them", "им, их", "кого? кому?"),
   word("see", "видеть"),
   word("other", "другой"),
   word("than", "чем (при сравнении)"),
   word("then", "тогда, затем"),
   word("now", "сейчас"),
   word("look", "смотреть"),
   word("only", "только"),
   word("come", "приходить"),
   word("its", "его, её", "чей? (о предмете)"),
   word("over", "над, через"),
   word("think", "думать"),
   word("also", "тоже, также"),
   word("back", "назад; спина"),
   word("after", "после"),
   word("use", "использовать"),
   word("two", "два"),
   word("how", "как (каким образом)"),
   word("our", "наш"),
   word("work", "работа, работать"),
   word("first", "первый"),
   word("well", "хорошо"),
   word("way", "путь, способ"),
   word("even", "даже"),
   word("new", "новый"),
   word("want", "хотеть"),
   word("because", "потому что"),
   word("any", "любой"),
   word("these", "эти"),
   word("give", "давать"),
   word("day", "день"),
   word("most", "большинство; самый"),
   word("us", "нам, нас"),
];

export const top100Course: Course = {
   id: "top100",
   title: "Топ-100 слов",
   description: "Сто самых частых английских слов",
   group: "Основа",
   style: "words",
   examStages: 4,
   levels: [0, 1, 2, 3].map((i) => ({
      id: `words-${i * 25 + 1}-${i * 25 + 25}`,
      title: `Слова ${i * 25 + 1}–${i * 25 + 25}`,
      items: WORDS.slice(i * 25, i * 25 + 25),
   })),
};
