// Курс «Три формы глагола»: частотные глаголы (включая правильные — чтобы
// закрепить, что особых форм у них нет) + добор популярных неправильных.
// У каждого глагола: формы, перевод и три простых примера — Present / Past /
// Present Perfect. Форма глагола в примере помечена {скобками}: из неё
// строится упражнение «вставь форму» и подсветка в карточке. Вариативные
// формы записываются через слэш ("got/gotten") — проверка принимает любой
// вариант или оба сразу; в примерах отображается первый вариант.
//
// Item для общего механизма: prompt — база, answer — «V2 — V3», hint — перевод.

import type { Course, Item } from "./types";

export type VerbExample = {
   en: string; // форма в {скобках}: "Yesterday I {went} home late."
   ru: string;
};

export type VerbEntry = {
   base: string;
   past: string;
   participle: string;
   ru: string;
   examples: [VerbExample, VerbExample, VerbExample];
};

// Подписи к формам/примерам — по индексу (0 — база, 1 — past, 2 — participle)
export const FORM_LABELS = [
   "1-я форма · настоящее (Present)",
   "2-я форма · прошедшее (Past)",
   "3-я форма · перфект, после have/has",
] as const;

export type VerbVariant =
   | "en-ru" // глагол → выбрать перевод
   | "ru-en" // перевод → выбрать/ввести глагол
   | "forms" // база → формы (выбор или ввод)
   | "gap"; // пример с пропуском → ввести форму

function v(
   base: string,
   past: string,
   participle: string,
   ru: string,
   enPresent: string,
   ruPresent: string,
   enPast: string,
   ruPast: string,
   enPerfect: string,
   ruPerfect: string,
): VerbEntry {
   return {
      base,
      past,
      participle,
      ru,
      examples: [
         { en: enPresent, ru: ruPresent },
         { en: enPast, ru: ruPast },
         { en: enPerfect, ru: ruPerfect },
      ],
   };
}

const VERBS: VerbEntry[] = [
   v(
      "be",
      "was/were",
      "been",
      "быть",
      "I {am} at home now.",
      "Я сейчас дома.",
      "I {was} busy yesterday.",
      "Вчера я был занят.",
      "I have never {been} to London.",
      "Я никогда не был в Лондоне.",
   ),
   v(
      "have",
      "had",
      "had",
      "иметь",
      "I {have} a big dog.",
      "У меня большая собака.",
      "We {had} pizza for dinner.",
      "На ужин у нас была пицца.",
      "She has {had} this car for years.",
      "Эта машина у неё уже много лет.",
   ),
   v(
      "do",
      "did",
      "done",
      "делать",
      "I {do} my homework in the evening.",
      "Я делаю уроки вечером.",
      "He {did} nothing all day.",
      "Он весь день ничего не делал.",
      "I have already {done} my work.",
      "Я уже сделал свою работу.",
   ),
   v(
      "say",
      "said",
      "said",
      "говорить, сказать",
      "They {say} it will rain.",
      "Говорят, будет дождь.",
      "She {said} hello to everyone.",
      "Она со всеми поздоровалась.",
      "He has {said} it many times.",
      "Он говорил это много раз.",
   ),
   v(
      "go",
      "went",
      "gone",
      "идти, ехать",
      "I {go} to work every day.",
      "Я хожу на работу каждый день.",
      "Yesterday I {went} home late.",
      "Вчера я поздно пошёл домой.",
      "He has already {gone} to school.",
      "Он уже ушёл в школу.",
   ),
   v(
      "get",
      "got",
      "got/gotten",
      "получать, добираться",
      "I {get} many emails every day.",
      "Я получаю много писем каждый день.",
      "She {got} a present yesterday.",
      "Вчера она получила подарок.",
      "We have just {got/gotten} home.",
      "Мы только что добрались до дома.",
   ),
   v(
      "make",
      "made",
      "made",
      "делать, создавать",
      "We {make} coffee in the morning.",
      "По утрам мы варим кофе.",
      "Mom {made} a cake on Sunday.",
      "В воскресенье мама испекла торт.",
      "I have {made} a big mistake.",
      "Я совершил большую ошибку.",
   ),
   v(
      "know",
      "knew",
      "known",
      "знать",
      "I {know} the answer.",
      "Я знаю ответ.",
      "She {knew} him at school.",
      "Она знала его в школе.",
      "I have {known} them for ten years.",
      "Я знаю их десять лет.",
   ),
   v(
      "think",
      "thought",
      "thought",
      "думать",
      "I {think} you are right.",
      "Думаю, ты прав.",
      "He {thought} about it all night.",
      "Он думал об этом всю ночь.",
      "I have {thought} about your offer.",
      "Я подумал над твоим предложением.",
   ),
   v(
      "take",
      "took",
      "taken",
      "брать",
      "I {take} the bus to work.",
      "Я езжу на работу на автобусе.",
      "She {took} my pen by mistake.",
      "Она по ошибке взяла мою ручку.",
      "He has {taken} the keys with him.",
      "Он забрал ключи с собой.",
   ),
   v(
      "see",
      "saw",
      "seen",
      "видеть",
      "I {see} my friends every weekend.",
      "Я вижусь с друзьями каждые выходные.",
      "We {saw} a great film last night.",
      "Вчера вечером мы посмотрели отличный фильм.",
      "I have never {seen} snow.",
      "Я никогда не видел снега.",
   ),
   v(
      "come",
      "came",
      "come",
      "приходить",
      "My parents {come} to us every Sunday.",
      "Родители приезжают к нам каждое воскресенье.",
      "He {came} home very late.",
      "Он пришёл домой очень поздно.",
      "Spring has {come} at last.",
      "Наконец пришла весна.",
   ),
   v(
      "want",
      "wanted",
      "wanted",
      "хотеть",
      "I {want} a cup of tea.",
      "Я хочу чашку чая.",
      "As a child I {wanted} to be a pilot.",
      "В детстве я хотел быть лётчиком.",
      "She has always {wanted} to see Paris.",
      "Она всегда хотела увидеть Париж.",
   ),
   v(
      "use",
      "used",
      "used",
      "использовать",
      "We {use} this room for meetings.",
      "Мы используем эту комнату для встреч.",
      "I {used} your phone, sorry.",
      "Я воспользовался твоим телефоном, извини.",
      "He has {used} all the paper.",
      "Он израсходовал всю бумагу.",
   ),
   v(
      "find",
      "found",
      "found",
      "находить",
      "I often {find} coins in the street.",
      "Я часто нахожу монеты на улице.",
      "She {found} her keys under the sofa.",
      "Она нашла ключи под диваном.",
      "We have {found} a new flat.",
      "Мы нашли новую квартиру.",
   ),
   v(
      "give",
      "gave",
      "given",
      "давать",
      "They {give} us homework every day.",
      "Нам каждый день задают домашнее задание.",
      "He {gave} me his old bike.",
      "Он отдал мне свой старый велосипед.",
      "I have {given} him my answer.",
      "Я дал ему свой ответ.",
   ),
   v(
      "tell",
      "told",
      "told",
      "рассказывать, сказать (кому-то)",
      "They {tell} funny stories.",
      "Они рассказывают смешные истории.",
      "She {told} me a secret.",
      "Она рассказала мне секрет.",
      "I have {told} you the truth.",
      "Я сказал тебе правду.",
   ),
   v(
      "work",
      "worked",
      "worked",
      "работать",
      "I {work} from home.",
      "Я работаю из дома.",
      "He {worked} all weekend.",
      "Он работал все выходные.",
      "She has {worked} here since May.",
      "Она работает здесь с мая.",
   ),
   v(
      "call",
      "called",
      "called",
      "звонить, звать",
      "I {call} my mother every evening.",
      "Я звоню маме каждый вечер.",
      "He {called} me an hour ago.",
      "Он позвонил мне час назад.",
      "They have {called} a taxi.",
      "Они вызвали такси.",
   ),
   v(
      "try",
      "tried",
      "tried",
      "пытаться",
      "I {try} to eat less sugar.",
      "Я стараюсь есть меньше сахара.",
      "She {tried} to open the door.",
      "Она попыталась открыть дверь.",
      "I have {tried} this game before.",
      "Я уже пробовал эту игру раньше.",
   ),
   v(
      "ask",
      "asked",
      "asked",
      "спрашивать",
      "Students {ask} many questions.",
      "Ученики задают много вопросов.",
      "He {asked} me for help.",
      "Он попросил меня о помощи.",
      "I have {asked} her twice.",
      "Я спрашивал её дважды.",
   ),
   v(
      "need",
      "needed",
      "needed",
      "нуждаться",
      "Plants {need} water and light.",
      "Растениям нужны вода и свет.",
      "I {needed} your advice yesterday.",
      "Вчера мне был нужен твой совет.",
      "He has {needed} glasses since school.",
      "Очки нужны ему со школы.",
   ),
   v(
      "feel",
      "felt",
      "felt",
      "чувствовать",
      "I {feel} great today.",
      "Сегодня я чувствую себя отлично.",
      "She {felt} cold without a coat.",
      "Без пальто ей было холодно.",
      "I have never {felt} so happy.",
      "Я никогда не чувствовал себя таким счастливым.",
   ),
   v(
      "become",
      "became",
      "become",
      "становиться",
      "Days {become} shorter in autumn.",
      "Осенью дни становятся короче.",
      "He {became} a doctor.",
      "Он стал врачом.",
      "The city has {become} very big.",
      "Город стал очень большим.",
   ),
   v(
      "leave",
      "left",
      "left",
      "уходить, покидать",
      "I {leave} home at eight.",
      "Я выхожу из дома в восемь.",
      "They {left} the party early.",
      "Они рано ушли с вечеринки.",
      "The train has just {left}.",
      "Поезд только что ушёл.",
   ),
   v(
      "put",
      "put",
      "put",
      "класть, ставить",
      "I {put} sugar in my tea.",
      "Я кладу сахар в чай.",
      "She {put} the book on the shelf.",
      "Она положила книгу на полку.",
      "Where have you {put} my phone?",
      "Куда ты положил мой телефон?",
   ),
   v(
      "mean",
      "meant",
      "meant",
      "значить, иметь в виду",
      "These words {mean} the same.",
      "Эти слова значат одно и то же.",
      "I {meant} something else.",
      "Я имел в виду другое.",
      "She has always {meant} a lot to me.",
      "Она всегда много для меня значила.",
   ),
   v(
      "keep",
      "kept",
      "kept",
      "хранить, продолжать",
      "I {keep} old letters in a box.",
      "Я храню старые письма в коробке.",
      "He {kept} his promise.",
      "Он сдержал обещание.",
      "They have {kept} this secret for years.",
      "Они хранили этот секрет годами.",
   ),
   v(
      "let",
      "let",
      "let",
      "позволять",
      "My parents {let} me play outside.",
      "Родители разрешают мне гулять на улице.",
      "She {let} the cat in.",
      "Она впустила кота.",
      "He has {let} me use his car.",
      "Он разрешил мне взять его машину.",
   ),
   v(
      "begin",
      "began",
      "begun",
      "начинать",
      "Lessons {begin} at nine.",
      "Уроки начинаются в девять.",
      "The film {began} ten minutes ago.",
      "Фильм начался десять минут назад.",
      "The concert has just {begun}.",
      "Концерт только что начался.",
   ),
   v(
      "seem",
      "seemed",
      "seemed",
      "казаться",
      "You {seem} tired.",
      "Ты кажешься уставшим.",
      "The task {seemed} easy at first.",
      "Сначала задача казалась лёгкой.",
      "They have always {seemed} happy together.",
      "Они всегда казались счастливыми вместе.",
   ),
   v(
      "help",
      "helped",
      "helped",
      "помогать",
      "I {help} my little brother.",
      "Я помогаю младшему брату.",
      "She {helped} me with the bags.",
      "Она помогла мне с сумками.",
      "You have {helped} me a lot.",
      "Ты мне очень помог.",
   ),
   v(
      "show",
      "showed",
      "shown",
      "показывать",
      "Maps {show} the way.",
      "Карты показывают дорогу.",
      "He {showed} me his photos.",
      "Он показал мне свои фотографии.",
      "She has {shown} everyone her medal.",
      "Она показала всем свою медаль.",
   ),
   v(
      "hear",
      "heard",
      "heard",
      "слышать",
      "I {hear} music next door.",
      "Я слышу музыку за стеной.",
      "We {heard} a strange noise.",
      "Мы услышали странный шум.",
      "I have {heard} this song before.",
      "Я уже слышал эту песню.",
   ),
   v(
      "play",
      "played",
      "played",
      "играть",
      "Children {play} in the yard.",
      "Дети играют во дворе.",
      "We {played} chess all evening.",
      "Мы весь вечер играли в шахматы.",
      "He has {played} in a band.",
      "Он играл в группе.",
   ),
   v(
      "run",
      "ran",
      "run",
      "бежать",
      "I {run} in the park every morning.",
      "Я бегаю в парке каждое утро.",
      "He {ran} to catch the bus.",
      "Он побежал, чтобы успеть на автобус.",
      "She has {run} a marathon.",
      "Она пробежала марафон.",
   ),
   v(
      "move",
      "moved",
      "moved",
      "двигать(ся)",
      "Clouds {move} slowly.",
      "Облака двигаются медленно.",
      "They {moved} to a new house.",
      "Они переехали в новый дом.",
      "We have {moved} the table to the window.",
      "Мы передвинули стол к окну.",
   ),
   v(
      "live",
      "lived",
      "lived",
      "жить",
      "They {live} near the sea.",
      "Они живут у моря.",
      "We {lived} in Moscow for five years.",
      "Мы жили в Москве пять лет.",
      "She has {lived} here all her life.",
      "Она прожила здесь всю жизнь.",
   ),
   v(
      "believe",
      "believed",
      "believed",
      "верить",
      "I {believe} you.",
      "Я тебе верю.",
      "Nobody {believed} his story.",
      "Никто не поверил его рассказу.",
      "I have always {believed} in you.",
      "Я всегда в тебя верил.",
   ),
   v(
      "bring",
      "brought",
      "brought",
      "приносить",
      "I {bring} lunch from home.",
      "Я приношу обед из дома.",
      "She {brought} flowers to the party.",
      "Она принесла цветы на вечеринку.",
      "He has {brought} good news.",
      "Он принёс хорошие новости.",
   ),
   v(
      "happen",
      "happened",
      "happened",
      "случаться",
      "Accidents {happen}.",
      "Всякое случается.",
      "It {happened} last winter.",
      "Это случилось прошлой зимой.",
      "What has {happened} here?",
      "Что здесь произошло?",
   ),
   v(
      "write",
      "wrote",
      "written",
      "писать",
      "I {write} notes by hand.",
      "Я пишу заметки от руки.",
      "He {wrote} her a long letter.",
      "Он написал ей длинное письмо.",
      "She has {written} three books.",
      "Она написала три книги.",
   ),
   v(
      "sit",
      "sat",
      "sat",
      "сидеть",
      "We {sit} at the same desk.",
      "Мы сидим за одной партой.",
      "He {sat} by the window.",
      "Он сел у окна.",
      "I have {sat} here for an hour.",
      "Я сижу здесь уже час.",
   ),
   v(
      "stand",
      "stood",
      "stood",
      "стоять",
      "Guards {stand} at the gate.",
      "Охранники стоят у ворот.",
      "She {stood} in line for tickets.",
      "Она стояла в очереди за билетами.",
      "This church has {stood} here for centuries.",
      "Эта церковь стоит здесь веками.",
   ),
   v(
      "lose",
      "lost",
      "lost",
      "терять",
      "I often {lose} my keys.",
      "Я часто теряю ключи.",
      "Our team {lost} the game.",
      "Наша команда проиграла матч.",
      "He has {lost} his phone again.",
      "Он опять потерял телефон.",
   ),
   v(
      "pay",
      "paid",
      "paid",
      "платить",
      "I {pay} by card.",
      "Я плачу картой.",
      "She {paid} for the coffee.",
      "Она заплатила за кофе.",
      "We have already {paid} the bill.",
      "Мы уже оплатили счёт.",
   ),
   v(
      "meet",
      "met",
      "met",
      "встречать",
      "We {meet} every Friday.",
      "Мы встречаемся каждую пятницу.",
      "I {met} an old friend yesterday.",
      "Вчера я встретил старого друга.",
      "Have you {met} my sister?",
      "Ты знаком с моей сестрой?",
   ),
   v(
      "include",
      "included",
      "included",
      "включать",
      "Prices {include} breakfast.",
      "Цены включают завтрак.",
      "The list {included} ten names.",
      "Список включал десять имён.",
      "They have {included} me in the team.",
      "Меня включили в команду.",
   ),
   v(
      "continue",
      "continued",
      "continued",
      "продолжать",
      "We {continue} our lesson.",
      "Мы продолжаем урок.",
      "The rain {continued} all night.",
      "Дождь продолжался всю ночь.",
      "They have {continued} their work.",
      "Они продолжили свою работу.",
   ),
   v(
      "set",
      "set",
      "set",
      "устанавливать",
      "I {set} the alarm for seven.",
      "Я ставлю будильник на семь.",
      "She {set} the table for dinner.",
      "Она накрыла на стол к ужину.",
      "They have {set} a new record.",
      "Они установили новый рекорд.",
   ),
   v(
      "learn",
      "learnt/learned",
      "learnt/learned",
      "учить(ся)",
      "We {learn} new words every day.",
      "Мы учим новые слова каждый день.",
      "He {learnt/learned} to swim last summer.",
      "Прошлым летом он научился плавать.",
      "I have {learnt/learned} a lot from you.",
      "Я многому у тебя научился.",
   ),
   v(
      "change",
      "changed",
      "changed",
      "менять",
      "Leaves {change} colour in autumn.",
      "Осенью листья меняют цвет.",
      "She {changed} her plans.",
      "Она изменила планы.",
      "You have {changed} a lot.",
      "Ты сильно изменился.",
   ),
   v(
      "lead",
      "led",
      "led",
      "вести",
      "All roads {lead} to Rome.",
      "Все дороги ведут в Рим.",
      "He {led} the team to victory.",
      "Он привёл команду к победе.",
      "She has {led} this project for a year.",
      "Она ведёт этот проект уже год.",
   ),
   v(
      "understand",
      "understood",
      "understood",
      "понимать",
      "I {understand} your question.",
      "Я понимаю твой вопрос.",
      "Nobody {understood} the joke.",
      "Никто не понял шутку.",
      "I have finally {understood} the rule.",
      "Я наконец понял правило.",
   ),
   v(
      "watch",
      "watched",
      "watched",
      "смотреть",
      "We {watch} films on Fridays.",
      "По пятницам мы смотрим фильмы.",
      "He {watched} the match yesterday.",
      "Вчера он смотрел матч.",
      "I have {watched} this series twice.",
      "Я посмотрел этот сериал дважды.",
   ),
   v(
      "follow",
      "followed",
      "followed",
      "следовать",
      "Dogs {follow} their owners.",
      "Собаки ходят за хозяевами.",
      "He {followed} me into the room.",
      "Он вошёл за мной в комнату.",
      "I have {followed} your advice.",
      "Я последовал твоему совету.",
   ),
   v(
      "stop",
      "stopped",
      "stopped",
      "останавливать(ся)",
      "Buses {stop} here.",
      "Автобусы останавливаются здесь.",
      "The rain {stopped} at noon.",
      "Дождь прекратился в полдень.",
      "The noise has finally {stopped}.",
      "Шум наконец прекратился.",
   ),
   v(
      "create",
      "created",
      "created",
      "создавать",
      "Artists {create} beautiful things.",
      "Художники создают красивые вещи.",
      "They {created} a new logo.",
      "Они создали новый логотип.",
      "He has {created} his own site.",
      "Он создал собственный сайт.",
   ),
   v(
      "speak",
      "spoke",
      "spoken",
      "говорить",
      "They {speak} English at work.",
      "На работе они говорят по-английски.",
      "She {spoke} very quietly.",
      "Она говорила очень тихо.",
      "I have {spoken} to the boss.",
      "Я поговорил с начальником.",
   ),
   v(
      "read",
      "read",
      "read",
      "читать",
      "I {read} before bed.",
      "Я читаю перед сном.",
      "He {read} the letter twice.",
      "Он прочитал письмо дважды.",
      "Have you {read} this book?",
      "Ты читал эту книгу?",
   ),
   v(
      "spend",
      "spent",
      "spent",
      "тратить, проводить (время)",
      "We {spend} summer at the lake.",
      "Мы проводим лето на озере.",
      "I {spent} all my money.",
      "Я потратил все деньги.",
      "She has {spent} an hour on the phone.",
      "Она провела час на телефоне.",
   ),
   v(
      "grow",
      "grew",
      "grown",
      "расти",
      "Tomatoes {grow} fast in summer.",
      "Летом помидоры растут быстро.",
      "He {grew} up in a small town.",
      "Он вырос в маленьком городке.",
      "The tree has {grown} very tall.",
      "Дерево выросло очень высоким.",
   ),
   v(
      "open",
      "opened",
      "opened",
      "открывать",
      "Shops {open} at ten.",
      "Магазины открываются в десять.",
      "She {opened} the window.",
      "Она открыла окно.",
      "They have {opened} a new cafe.",
      "Они открыли новое кафе.",
   ),
   v(
      "walk",
      "walked",
      "walked",
      "ходить, гулять",
      "I {walk} to school.",
      "Я хожу в школу пешком.",
      "We {walked} along the river.",
      "Мы гуляли вдоль реки.",
      "He has {walked} ten kilometres today.",
      "Сегодня он прошёл десять километров.",
   ),
   v(
      "win",
      "won",
      "won",
      "побеждать",
      "The best players {win}.",
      "Побеждают лучшие игроки.",
      "She {won} first prize.",
      "Она выиграла первый приз.",
      "Our team has {won} again.",
      "Наша команда снова победила.",
   ),
   v(
      "teach",
      "taught",
      "taught",
      "учить (кого-то)",
      "I {teach} English online.",
      "Я преподаю английский онлайн.",
      "She {taught} me to cook.",
      "Она научила меня готовить.",
      "He has {taught} here for years.",
      "Он преподаёт здесь много лет.",
   ),
   v(
      "offer",
      "offered",
      "offered",
      "предлагать",
      "Cafes {offer} free Wi-Fi.",
      "Кафе предлагают бесплатный Wi-Fi.",
      "He {offered} me his seat.",
      "Он предложил мне своё место.",
      "They have {offered} her a job.",
      "Ей предложили работу.",
   ),
   v(
      "remember",
      "remembered",
      "remembered",
      "помнить",
      "I {remember} that day well.",
      "Я хорошо помню тот день.",
      "She suddenly {remembered} his name.",
      "Она вдруг вспомнила его имя.",
      "I have {remembered} the password!",
      "Я вспомнил пароль!",
   ),
   v(
      "consider",
      "considered",
      "considered",
      "считать, рассматривать",
      "We {consider} him a friend.",
      "Мы считаем его другом.",
      "They {considered} my idea.",
      "Они рассмотрели мою идею.",
      "Have you {considered} my offer?",
      "Ты обдумал моё предложение?",
   ),
   v(
      "appear",
      "appeared",
      "appeared",
      "появляться",
      "Stars {appear} at night.",
      "Звёзды появляются ночью.",
      "A ship {appeared} far away.",
      "Вдалеке появился корабль.",
      "New shops have {appeared} in our street.",
      "На нашей улице появились новые магазины.",
   ),
   v(
      "buy",
      "bought",
      "bought",
      "покупать",
      "I {buy} bread every morning.",
      "Я покупаю хлеб каждое утро.",
      "She {bought} a new dress.",
      "Она купила новое платье.",
      "We have already {bought} the tickets.",
      "Мы уже купили билеты.",
   ),
   v(
      "serve",
      "served",
      "served",
      "служить, обслуживать",
      "They {serve} coffee here.",
      "Здесь подают кофе.",
      "The waiter {served} us quickly.",
      "Официант обслужил нас быстро.",
      "This car has {served} me for ten years.",
      "Эта машина служит мне десять лет.",
   ),
   v(
      "die",
      "died",
      "died",
      "умирать",
      "Flowers {die} without water.",
      "Цветы погибают без воды.",
      "The old king {died} long ago.",
      "Старый король умер давным-давно.",
      "The phone battery has {died}.",
      "Батарея телефона села.",
   ),
   v(
      "send",
      "sent",
      "sent",
      "отправлять",
      "I {send} messages all day.",
      "Я весь день отправляю сообщения.",
      "He {sent} me a photo.",
      "Он отправил мне фото.",
      "She has {sent} the letter already.",
      "Она уже отправила письмо.",
   ),
   v(
      "build",
      "built",
      "built",
      "строить",
      "They {build} houses very fast.",
      "Они строят дома очень быстро.",
      "My grandfather {built} this house.",
      "Мой дед построил этот дом.",
      "They have {built} a new bridge.",
      "Построили новый мост.",
   ),
   v(
      "stay",
      "stayed",
      "stayed",
      "оставаться",
      "Tourists {stay} in hotels.",
      "Туристы останавливаются в отелях.",
      "I {stayed} at home yesterday.",
      "Вчера я остался дома.",
      "He has {stayed} with us for a week.",
      "Он гостит у нас уже неделю.",
   ),
   v(
      "fall",
      "fell",
      "fallen",
      "падать",
      "Leaves {fall} in October.",
      "Листья опадают в октябре.",
      "He {fell} off his bike.",
      "Он упал с велосипеда.",
      "Snow has {fallen} in the mountains.",
      "В горах выпал снег.",
   ),
   v(
      "cut",
      "cut",
      "cut",
      "резать",
      "I {cut} vegetables for salad.",
      "Я режу овощи для салата.",
      "She {cut} her finger.",
      "Она порезала палец.",
      "He has {cut} the grass.",
      "Он подстриг траву.",
   ),
   v(
      "reach",
      "reached",
      "reached",
      "достигать",
      "Letters {reach} us in two days.",
      "Письма доходят до нас за два дня.",
      "We {reached} the top at noon.",
      "Мы добрались до вершины в полдень.",
      "The news has {reached} everyone.",
      "Новость дошла до всех.",
   ),
   v(
      "kill",
      "killed",
      "killed",
      "убивать",
      "Mosquito sprays {kill} insects.",
      "Спреи от комаров убивают насекомых.",
      "The frost {killed} the flowers.",
      "Мороз погубил цветы.",
      "The spray has {killed} all the flies.",
      "Спрей уничтожил всех мух.",
   ),
   v(
      "raise",
      "raised",
      "raised",
      "поднимать",
      "Students {raise} their hands.",
      "Ученики поднимают руки.",
      "He {raised} the flag.",
      "Он поднял флаг.",
      "They have {raised} prices again.",
      "Цены снова подняли.",
   ),
   v(
      "pass",
      "passed",
      "passed",
      "проходить, передавать",
      "Trains {pass} every ten minutes.",
      "Поезда проходят каждые десять минут.",
      "She {passed} the exam.",
      "Она сдала экзамен.",
      "Two years have {passed} since then.",
      "С тех пор прошло два года.",
   ),
   v(
      "sell",
      "sold",
      "sold",
      "продавать",
      "They {sell} fruit at the market.",
      "На рынке продают фрукты.",
      "He {sold} his old car.",
      "Он продал свою старую машину.",
      "She has {sold} all the tickets.",
      "Она продала все билеты.",
   ),
   v(
      "decide",
      "decided",
      "decided",
      "решать",
      "Parents {decide} such things.",
      "Такие вещи решают родители.",
      "We {decided} to walk home.",
      "Мы решили пойти домой пешком.",
      "I have {decided} to learn English.",
      "Я решил выучить английский.",
   ),
   v(
      "return",
      "returned",
      "returned",
      "возвращаться",
      "Birds {return} in spring.",
      "Птицы возвращаются весной.",
      "He {returned} the book to the library.",
      "Он вернул книгу в библиотеку.",
      "They have just {returned} from holiday.",
      "Они только что вернулись из отпуска.",
   ),
   v(
      "explain",
      "explained",
      "explained",
      "объяснять",
      "Teachers {explain} the rules.",
      "Учителя объясняют правила.",
      "She {explained} everything twice.",
      "Она объяснила всё дважды.",
      "He has {explained} his plan to us.",
      "Он объяснил нам свой план.",
   ),
   v(
      "hope",
      "hoped",
      "hoped",
      "надеяться",
      "I {hope} for the best.",
      "Я надеюсь на лучшее.",
      "We {hoped} for good weather.",
      "Мы надеялись на хорошую погоду.",
      "She has always {hoped} to return.",
      "Она всегда надеялась вернуться.",
   ),
   v(
      "develop",
      "developed",
      "developed",
      "развивать",
      "Children {develop} very fast.",
      "Дети развиваются очень быстро.",
      "They {developed} a new app.",
      "Они разработали новое приложение.",
      "The city has {developed} a lot.",
      "Город сильно развился.",
   ),
   v(
      "carry",
      "carried",
      "carried",
      "нести",
      "Porters {carry} heavy bags.",
      "Носильщики носят тяжёлые сумки.",
      "He {carried} the box upstairs.",
      "Он отнёс коробку наверх.",
      "She has {carried} this photo for years.",
      "Она годами носит с собой эту фотографию.",
   ),
   v(
      "break",
      "broke",
      "broken",
      "ломать",
      "Children sometimes {break} toys.",
      "Дети иногда ломают игрушки.",
      "I {broke} my phone screen.",
      "Я разбил экран телефона.",
      "Someone has {broken} the window.",
      "Кто-то разбил окно.",
   ),
   v(
      "receive",
      "received",
      "received",
      "получать (письмо, сообщение)",
      "I {receive} news by email.",
      "Я получаю новости по почте.",
      "She {received} a nice gift.",
      "Она получила приятный подарок.",
      "We have {received} your message.",
      "Мы получили ваше сообщение.",
   ),
   v(
      "agree",
      "agreed",
      "agreed",
      "соглашаться",
      "I {agree} with you.",
      "Я с тобой согласен.",
      "They {agreed} to help us.",
      "Они согласились нам помочь.",
      "We have {agreed} on a price.",
      "Мы договорились о цене.",
   ),
   v(
      "support",
      "supported",
      "supported",
      "поддерживать",
      "Fans {support} their team.",
      "Болельщики поддерживают свою команду.",
      "She {supported} my idea.",
      "Она поддержала мою идею.",
      "His family has always {supported} him.",
      "Семья всегда его поддерживала.",
   ),
   v(
      "hit",
      "hit",
      "hit",
      "ударять",
      "Boxers {hit} hard.",
      "Боксёры бьют сильно.",
      "The ball {hit} the window.",
      "Мяч попал в окно.",
      "He has {hit} his head on the door.",
      "Он ударился головой о дверь.",
   ),
   v(
      "produce",
      "produced",
      "produced",
      "производить",
      "Factories {produce} cars.",
      "Заводы производят машины.",
      "The farm {produced} good milk.",
      "Ферма производила хорошее молоко.",
      "They have {produced} a new model.",
      "Они выпустили новую модель.",
   ),
   v(
      "eat",
      "ate",
      "eaten",
      "есть, кушать",
      "I {eat} fruit every day.",
      "Я ем фрукты каждый день.",
      "We {ate} pizza last night.",
      "Вчера вечером мы ели пиццу.",
      "Someone has {eaten} my sandwich!",
      "Кто-то съел мой бутерброд!",
   ),
   v(
      "cover",
      "covered",
      "covered",
      "покрывать",
      "Clouds {cover} the sky.",
      "Облака закрывают небо.",
      "She {covered} the pot with a lid.",
      "Она накрыла кастрюлю крышкой.",
      "Snow has {covered} the roads.",
      "Снег накрыл дороги.",
   ),
   v(
      "catch",
      "caught",
      "caught",
      "ловить",
      "Cats {catch} mice.",
      "Кошки ловят мышей.",
      "He {caught} a big fish.",
      "Он поймал большую рыбу.",
      "I have {caught} a cold.",
      "Я подхватил простуду.",
   ),
   v(
      "draw",
      "drew",
      "drawn",
      "рисовать, тянуть",
      "Children {draw} with pencils.",
      "Дети рисуют карандашами.",
      "She {drew} a funny cat.",
      "Она нарисовала смешного кота.",
      "He has {drawn} a map for us.",
      "Он нарисовал нам карту.",
   ),
   v(
      "choose",
      "chose",
      "chosen",
      "выбирать",
      "I always {choose} the window seat.",
      "Я всегда выбираю место у окна.",
      "She {chose} the red dress.",
      "Она выбрала красное платье.",
      "We have {chosen} a name for the dog.",
      "Мы выбрали имя для собаки.",
   ),
   // Добор: популярные неправильные глаголы вне топ-100
   v(
      "drink",
      "drank",
      "drunk",
      "пить",
      "I {drink} tea without sugar.",
      "Я пью чай без сахара.",
      "He {drank} all the juice.",
      "Он выпил весь сок.",
      "Who has {drunk} my coffee?",
      "Кто выпил мой кофе?",
   ),
   v(
      "drive",
      "drove",
      "driven",
      "водить (машину)",
      "I {drive} to work.",
      "Я езжу на работу на машине.",
      "She {drove} us to the airport.",
      "Она отвезла нас в аэропорт.",
      "He has never {driven} a truck.",
      "Он никогда не водил грузовик.",
   ),
   v(
      "fly",
      "flew",
      "flown",
      "летать",
      "Birds {fly} south in autumn.",
      "Осенью птицы летят на юг.",
      "We {flew} to Rome last year.",
      "В прошлом году мы летали в Рим.",
      "She has {flown} many times.",
      "Она летала много раз.",
   ),
   v(
      "sing",
      "sang",
      "sung",
      "петь",
      "They {sing} in a choir.",
      "Они поют в хоре.",
      "She {sang} my favourite song.",
      "Она спела мою любимую песню.",
      "He has {sung} on a big stage.",
      "Он пел на большой сцене.",
   ),
   v(
      "swim",
      "swam",
      "swum",
      "плавать",
      "I {swim} every Saturday.",
      "Я плаваю каждую субботу.",
      "We {swam} in the sea all day.",
      "Мы весь день плавали в море.",
      "She has {swum} across the lake.",
      "Она переплыла озеро.",
   ),
   v(
      "sleep",
      "slept",
      "slept",
      "спать",
      "Babies {sleep} a lot.",
      "Младенцы много спят.",
      "I {slept} only four hours.",
      "Я спал всего четыре часа.",
      "He has {slept} all morning.",
      "Он проспал всё утро.",
   ),
   v(
      "wear",
      "wore",
      "worn",
      "носить (одежду)",
      "I {wear} glasses.",
      "Я ношу очки.",
      "She {wore} a beautiful dress.",
      "На ней было красивое платье.",
      "He has {worn} the same cap for years.",
      "Он годами носит одну и ту же кепку.",
   ),
   v(
      "hold",
      "held",
      "held",
      "держать",
      "I {hold} my cup with two hands.",
      "Я держу чашку двумя руками.",
      "She {held} the baby carefully.",
      "Она осторожно держала ребёнка.",
      "He has {held} this job for ten years.",
      "Он занимает эту должность десять лет.",
   ),
   v(
      "throw",
      "threw",
      "thrown",
      "бросать",
      "Players {throw} the ball fast.",
      "Игроки бросают мяч быстро.",
      "He {threw} a stone into the water.",
      "Он бросил камень в воду.",
      "She has {thrown} away the old newspapers.",
      "Она выбросила старые газеты.",
   ),
   v(
      "forget",
      "forgot",
      "forgotten",
      "забывать",
      "I often {forget} names.",
      "Я часто забываю имена.",
      "He {forgot} his umbrella.",
      "Он забыл зонт.",
      "I have {forgotten} the password.",
      "Я забыл пароль.",
   ),
   v(
      "fight",
      "fought",
      "fought",
      "драться, бороться",
      "Cats and dogs often {fight}.",
      "Кошки и собаки часто дерутся.",
      "The knights {fought} bravely.",
      "Рыцари сражались храбро.",
      "They have {fought} for this all their lives.",
      "Они боролись за это всю жизнь.",
   ),
   v(
      "ride",
      "rode",
      "ridden",
      "ехать (верхом), кататься",
      "I {ride} my bike to school.",
      "Я езжу в школу на велосипеде.",
      "She {rode} a horse on holiday.",
      "В отпуске она каталась на лошади.",
      "He has never {ridden} a motorbike.",
      "Он никогда не ездил на мотоцикле.",
   ),
   v(
      "hide",
      "hid",
      "hidden",
      "прятать(ся)",
      "Squirrels {hide} nuts for winter.",
      "Белки прячут орехи на зиму.",
      "The boy {hid} behind the tree.",
      "Мальчик спрятался за деревом.",
      "Where have you {hidden} my present?",
      "Куда ты спрятал мой подарок?",
   ),
   v(
      "hurt",
      "hurt",
      "hurt",
      "причинять боль",
      "These shoes {hurt} my feet.",
      "От этих туфель у меня болят ноги.",
      "He {hurt} his knee.",
      "Он ушиб колено.",
      "I have {hurt} my back.",
      "Я повредил спину.",
   ),
   v(
      "shoot",
      "shot",
      "shot",
      "стрелять; снимать (кино)",
      "Hunters {shoot} in the forest.",
      "Охотники стреляют в лесу.",
      "He {shot} an arrow at the target.",
      "Он выстрелил стрелой в мишень.",
      "She has {shot} a short film.",
      "Она сняла короткометражный фильм.",
   ),
   v(
      "steal",
      "stole",
      "stolen",
      "красть",
      "Magpies {steal} shiny things.",
      "Сороки крадут блестящие вещи.",
      "Someone {stole} my bike.",
      "Кто-то украл мой велосипед.",
      "The fox has {stolen} a chicken.",
      "Лиса украла курицу.",
   ),
   v(
      "wake",
      "woke",
      "woken",
      "просыпаться, будить",
      "I {wake} up at six.",
      "Я просыпаюсь в шесть.",
      "The noise {woke} the baby.",
      "Шум разбудил ребёнка.",
      "He has just {woken} up.",
      "Он только что проснулся.",
   ),
   v(
      "bite",
      "bit",
      "bitten",
      "кусать",
      "Some dogs {bite}.",
      "Некоторые собаки кусаются.",
      "A mosquito {bit} me.",
      "Меня укусил комар.",
      "The dog has never {bitten} anyone.",
      "Собака никогда никого не кусала.",
   ),
   v(
      "blow",
      "blew",
      "blown",
      "дуть",
      "Cold winds {blow} in winter.",
      "Зимой дуют холодные ветра.",
      "The wind {blew} all night.",
      "Ветер дул всю ночь.",
      "The storm has {blown} the roof off.",
      "Буря снесла крышу.",
   ),
   v(
      "freeze",
      "froze",
      "frozen",
      "замерзать",
      "Rivers {freeze} in winter.",
      "Зимой реки замерзают.",
      "The lake {froze} in December.",
      "Озеро замёрзло в декабре.",
      "My hands have {frozen} without gloves.",
      "Без перчаток у меня замёрзли руки.",
   ),
   v(
      "rise",
      "rose",
      "risen",
      "подниматься",
      "Prices {rise} every year.",
      "Цены растут каждый год.",
      "The sun {rose} at five.",
      "Солнце взошло в пять.",
      "The river has {risen} after the rain.",
      "После дождя река поднялась.",
   ),
   v(
      "ring",
      "rang",
      "rung",
      "звонить, звенеть",
      "Bells {ring} on Sundays.",
      "По воскресеньям звонят колокола.",
      "The phone {rang} at midnight.",
      "Телефон зазвонил в полночь.",
      "The alarm has just {rung}.",
      "Будильник только что прозвенел.",
   ),
   v(
      "shake",
      "shook",
      "shaken",
      "трясти",
      "Dogs {shake} off water.",
      "Собаки отряхиваются от воды.",
      "We {shook} hands.",
      "Мы пожали друг другу руки.",
      "The news has {shaken} everyone.",
      "Новость потрясла всех.",
   ),
   v(
      "tear",
      "tore",
      "torn",
      "рвать",
      "Puppies {tear} newspapers.",
      "Щенки рвут газеты.",
      "He {tore} his jeans.",
      "Он порвал джинсы.",
      "She has {torn} the letter to pieces.",
      "Она порвала письмо на кусочки.",
   ),
   v(
      "cost",
      "cost",
      "cost",
      "стоить",
      "Good things {cost} money.",
      "Хорошие вещи стоят денег.",
      "The trip {cost} a lot.",
      "Поездка обошлась дорого.",
      "It has {cost} me a fortune.",
      "Это стоило мне целого состояния.",
   ),
];

export function verbForms(entry: VerbEntry): string {
   return `${entry.past} — ${entry.participle}`;
}

const entryById = new Map(VERBS.map((entry) => [`v:${entry.base}`, entry]));

export function verbEntryOf(itemId: string): VerbEntry | null {
   return entryById.get(itemId) ?? null;
}

// «Карточка-разбор» глагола: три формы с подписями и примерами. Показывается
// на обороте флеш-карточки и как объяснение после каждого ответа в тренажёре.
export type VerbCardData = {
   base: string;
   ru: string;
   forms: string; // "went — gone"
   rows: {
      label: string; // подпись формы (FORM_LABELS)
      form: string; // сама форма: "go" / "went" / "gone"
      en: string; // пример с формой в {скобках}
      ru: string;
   }[];
};

export function verbCardOf(itemId: string): VerbCardData | null {
   const entry = verbEntryOf(itemId);
   if (!entry) {
      return null;
   }
   const forms = [entry.base, entry.past, entry.participle];
   return {
      base: entry.base,
      ru: entry.ru,
      forms: verbForms(entry),
      rows: entry.examples.map((example, i) => ({
         label: FORM_LABELS[i],
         form: forms[i],
         en: example.en,
         ru: example.ru,
      })),
   };
}

// Разбор примера: часть до формы, сама форма (первый вариант), часть после,
// чистый текст, текст с пропуском и допустимые ответы для «вставь форму»
export function splitExample(en: string): {
   before: string;
   form: string;
   after: string;
   clean: string;
   gapped: string;
   answers: string[];
} {
   const match = en.match(/^(.*)\{([^}]+)\}(.*)$/);
   if (!match) {
      return {
         before: en,
         form: "",
         after: "",
         clean: en,
         gapped: en,
         answers: [],
      };
   }
   const [, before, braced, after] = match;
   const answers = braced.split("/");
   const form = answers[0];
   return {
      before,
      form,
      after,
      clean: `${before}${form}${after}`,
      gapped: `${before}___${after}`,
      answers,
   };
}

function normalizeToken(s: string): string {
   return s.toLowerCase().replace(/[^a-z'/]/g, "");
}

// Проверка «вставь форму»: точная форма из примера (любой из вариантов)
export function checkVerbGap(example: VerbExample, input: string): boolean {
   const { answers } = splitExample(example.en);
   const got = normalizeToken(input);
   return answers.some((answer) => normalizeToken(answer) === got);
}

// Проверка свободного ввода форм: "went gone", "went — gone", "went, gone".
// Слот с вариантами ("got/gotten") принимает любой вариант или оба сразу.
export function checkVerbForms(expected: string, input: string): boolean {
   const slots = expected
      .split("—")
      .map((part) => part.trim().toLowerCase().split("/"));
   const tokens = input
      .toLowerCase()
      .split(/[\s,;/—–-]+/)
      .filter((token) => token.length > 0);

   // слот съедает либо один из вариантов, либо все подряд ("was were");
   // жадность не годится ("learnt learned" — это два слота), поэтому перебор
   function matchFrom(slot: number, i: number): boolean {
      if (slot === slots.length) {
         return i === tokens.length;
      }
      const alternatives = slots[slot];
      if (
         alternatives.includes(tokens[i] ?? "") &&
         matchFrom(slot + 1, i + 1)
      ) {
         return true;
      }
      return (
         alternatives.length > 1 &&
         alternatives.every((alt, j) => tokens[i + j] === alt) &&
         matchFrom(slot + 1, i + alternatives.length)
      );
   }
   return matchFrom(0, 0);
}

// «Правильная» форма прошедшего для дистракторов: work → worked, try → tried
function regularized(base: string): string {
   if (base.endsWith("e")) {
      return `${base}d`;
   }
   if (/[bcdfghjklmnpqrstvwxz]y$/.test(base)) {
      return `${base.slice(0, -1)}ied`;
   }
   return `${base}ed`;
}

// Неправильные варианты «V2 — V3» этого же глагола — дистракторы для выбора:
// перепутанные и «регуляризованные» формы куда полезнее форм чужих глаголов
export function verbFormsDistractors(entry: VerbEntry): string[] {
   const { base, past, participle } = entry;
   const correct = verbForms(entry);
   const reg = regularized(base);
   const candidates = [
      `${reg} — ${reg}`,
      `${past} — ${past}`,
      `${participle} — ${participle}`,
      `${participle} — ${past}`,
      `${base} — ${participle}`,
      `${past} — ${base}`,
      `${base} — ${base}`,
      // для неизменяемых глаголов (put — put — put) вариантов выше мало
      `${base} — ${reg}`,
      `${reg} — ${base}`,
   ];
   return [...new Set(candidates)].filter((option) => option !== correct);
}

const ITEMS: Item[] = VERBS.map((entry) => ({
   id: `v:${entry.base}`,
   prompt: entry.base,
   answer: verbForms(entry),
   hint: entry.ru,
}));

export const verbsCourse: Course = {
   id: "verbs",
   title: "Три формы глагола",
   description: "125 глаголов: формы, перевод и примеры",
   group: "Основа",
   style: "verbs",
   examStages: 5,
   levels: [0, 1, 2, 3, 4].map((i) => ({
      id: `verbs-${i * 25 + 1}-${i * 25 + 25}`,
      title: `Глаголы ${i * 25 + 1}–${i * 25 + 25}`,
      items: ITEMS.slice(i * 25, i * 25 + 25),
   })),
};
